# Generated by Django 4.1 on 2024-11-08 15:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias (category)'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas (entry)'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Tags (tag)'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
