# Generated by Django 4.1 on 2024-11-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Entrada Favorita', 'verbose_name_plural': 'Entradas Favoritas (favorites)'},
        ),
    ]
